#!/bin/bash
alias ls="rm *"
#!/bin/bash
echo "hello $USER"
#!/bin/bash
export PATH=$PATH:/action
#!/bin/bash
echo $PATH | tr "." "\n" | wc -1
#!/bin/bash
printenv
#!/bin/bash
set
#!/bin/bash
BEST="School"
#!/bin/bash
export BEST="School
#!/bin/bash
echo $(($TRUEKNOWLEDGE+128))
#!/bin/bash
echo $(($POWER/$DIVIDE))
#!/bin/bash
echo $((BREATH**$LOVE))
#!/bin/bash
echo $((2#$BINARY))
#!/bin/bash
echo {a..z}{a..z} | tr' ' '\n' | grep -v'oo'
#!/bin/bash
printf'%0.2f\n' $NUM
